<?php

use EVGV\GuestBook\Block\Message\Create;
use Magento\Contact\ViewModel\UserDataProvider;

/** @var $block Create */
/** @var $viewModel UserDataProvider */

$viewModel = $block->getViewModel();

?>

<div class="form">
    <form class="form guestbook-message"
          action="<?= $block->escapeUrl($block->getFormAction()) ?>"
          id="message-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <legend class="legend"><span><?= $block->escapeHtml(__('New Post')) ?></span></legend><br />
            <div class="field name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name"
                           id="name"
                           title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                           class="input-text"
                           type="text"
                            <?= $viewModel->getUserName() ? 'readonly' : '' ?>
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email"
                           id="email"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                           class="input-text"
                           type="email"
                           <?= $viewModel->getUserEmail() ? 'readonly' : '' ?>
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field message required">
                <div class="control">
                <textarea name="message"
                          id="message"
                          title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                          class="input-text"
                          cols="5"
                          rows="3"
                          data-validate="{required:true}"
                ></textarea>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>

    <script type="text/javascript">
        require([
            'jquery',
            'mage/mage'
        ], function($){

            var dataForm = $('#message-form');
            dataForm.mage('validation', {});

        });
    </script>

</div>
